services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 2717:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
